name: id_pair_set
description: A Dart package providing an immutable data structure for managing unique ID pairs by type, with features for filtering, serialization, and validation.
version: 1.2.1
repository: https://github.com/staylorx/id_pair_set
issue_tracker: https://github.com/staylorx/id_pair_set/issues
documentation: https://github.com/staylorx/id_pair_set

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
